config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
           :controllers  => {
             :registrations => 'my_devise/registrations',
             :omniauth_callbacks => 'users/omniauth_callbacks'

           }

  resources :bookmarks, only: [:index, :new, :destroy]

  post 'reviews/upvote'
  post 'ideas/filter', to: "ideas#index"

  scope '(:locale)', locale: /fr|en/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    post '/rate' => 'rater#create', :as => 'rate'
    # get 'bookmarks/index'
    # get 'bookmarks/new'
    # get 'bookmarks/destroy'


    resources :pro_profiles
    resources :boxes
    resources :ideas  do
      resources :reviews
    end



    get 'ideas/index_rating'

    resources :profiles

    # post 'profiles/bookmark'
    # post 'profiles/bookmarked_ideas'
    get 'states', to: 'profiles#states'
    get 'cities', to: 'profiles#cities'
    get 'my_profile', to: 'profiles#my_profile'

    get 'cgu', to: 'pages#cgu'


    root to: 'ideas#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :profile
  has_many :reviews
  has_many :idea_boxes
  has_many :profile_tags
  has_many :boxes, through: :idea_boxes
  has_many :pro_profiles, through: :profile_tags
  has_many :bookmarks

  mount_uploader :photo, PhotoUploader

  ratyrate_rateable "rate"

  validates :title,
          :presence => {:message => "Vous devez ajouter un titre" },
          :uniqueness => {:message => "Ce titre existe déjà"},
          :length => { :maximum => 40, :message => "Votre titre doit avoir moins de 40 caractères"}
  validates :description,
          :presence => {:message => "Vous devez avoir une description" },
          :length => { :maximum => 240, :message => "Votre description doit avoir moins de 240 caractères"}
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: [0,1,2,3,4,5] }

  STATUTES = ["brouillon", "publié"]
  validates :status, inclusion: {in: STATUTES}
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  skip_before_action :verify_authenticity_token, raise: false

  def index
    if current_user
      @profile = Profile.find_by(user_id: current_user.id)
      @pro_profile = ProProfile.find_by(user_id: current_user.id)
    end
    if params[:query].present?
      sql_query = " \
        ideas.title ILIKE :query \
        OR ideas.description ILIKE :query \
        OR ideas.country ILIKE :query \
        OR ideas.state ILIKE :query \
        OR ideas.city ILIKE :query \
      "
      @ideas = policy_scope(Idea).where(status: "publié").where(sql_query, query: "%#{params[:query]}%")
    else
      @ideas = policy_scope(Idea).where(status: "publié")
    end
    if request.post?
      if params[:city]
       @ideas = @ideas.where(city: params[:city])
      elsif params[:state]
        @ideas = @ideas.where(state: params[:state])
      elsif params[:country]
        @ideas = @ideas.where(country: params[:country])
      end
    end
    if params[:order] == "date"
      @ideas = @ideas.order(created_at: :desc)
    elsif params[:order] == "popularity"
      @ideas_and_number_of_vote = []
      @ideas = @ideas.each do |idea|
        @ideas_and_number_of_vote << [ Rate.where(rateable_id: idea.id).count, idea]
      end
      @ideas = []
      @ideas_and_number_of_vote.sort.reverse.each do |idea|
        @ideas << idea[1]
      end
    elsif params[:order] == "rating"
      @ideas_and_avg_rating = []
      @ideas = @ideas.each do |idea|
        @ideas_and_avg_rating << [ Rate.avg(idea) + Rate.score_range(idea), idea]
      end
      @ideas = []
      @ideas_and_avg_rating.sort.reverse.each do |idea|
        @ideas << idea[1]
      end
    else
      @ideas = @ideas.order(created_at: :desc)
    end
  end

  def index_rating
    @ideas_and_avg_rating = []
    policy_scope(Idea).where(status: "publié").each do |idea|
      @ideas_and_avg_rating << [ Rate.avg(idea), idea]
    end
    @ideas = []
    @ideas_and_avg_rating.sort.reverse.each do |idea|
      @ideas << idea[1]
    end
  end

  def show
    @review = Review.new
    authorize @idea
  end

  def new
    @profile = Profile.find_by(user_id: current_user.id)
    @idea = Idea.new
    authorize @idea
  end

  def create
    @user = User.find(current_user.id)
    @profile = Profile.find_by(user_id: @user.id)
    @idea = Idea.new(idea_params)
    authorize @idea
    @idea.profile_id = @profile.id
    @idea.rating = 0
    if publishing?
      @idea.status = "publié"
    elsif saving_as_draft?
      @idea.status = "brouillon"
    end
    if @idea.valid?
      @idea.save
      redirect_to idea_path(@idea)
    else
      render :new
    end
  end

  def edit
    @profile_tags = ProfileTag.all.where(idea_id: @idea.id)
    @idea_boxes = IdeaBox.all.where(idea_id: @idea.id)
    authorize @idea
  end

  def update
    @idea.update(idea_params)
    @idea.boxes.clear
    if @idea.country == ""
      @idea.country = nil
    end
    if @idea.state == ""
      @idea.state = nil
    end
    if @idea.city == ""
      @idea.city = nil
    end
    if params[:idea][:box_ids]
      params[:idea][:box_ids].each do |id|
        @idea.boxes << Box.find(id)
      end
    end
    @idea.pro_profiles.clear
    if params[:idea][:pro_profile_ids]
      params[:idea][:pro_profile_ids].each do |id|
        @idea.pro_profiles << ProProfile.find(id)
      end
    end
    authorize @idea
    @idea.rating = 0

    if @idea.status == "publié" && params[:commit] == "Mettre à jour" || @idea.status == "publié" && params[:commit] == "Edit"
      @idea.status = "publié"
    elsif @idea.status == "brouillon" && params[:commit] == "Mettre à jour"
      @idea.status = "publié"
    elsif @idea.status == "publié" && params[:commit] == "Sauvegarder"
      @idea.status = "brouillon"
    elsif @idea.status == "brouillon" && params[:commit] == "Sauvegarder"
      @idea.status = "brouillon"
    end

    if @idea.save
      redirect_to idea_path(@idea)
    else
      redirect_to edit_idea_path(@idea)
    end
  end

  def destroy
    authorize @idea
    @idea.destroy
    redirect_to ideas_path
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description, :rating, :status, :photo, :country, :state, :city, box_ids: [], pro_profile_ids: [])
  end

  def set_idea
    @idea = Idea.find(params[:id])
  end

  def publishing?
    params[:commit] == "Postez"
  end

  def saving_as_draft?
    params[:commit] == "Sauvegarder"
  end
end

app/views/ideas/create.html.erb
<h1>Ideas#create</h1>
<p>Find me in app/views/ideas/create.html.erb</p>

app/views/ideas/destroy.html.erb
<h1>Ideas#destroy</h1>
<p>Find me in app/views/ideas/destroy.html.erb</p>

app/views/ideas/edit.html.erb
 <div class="container">
    <div class="col s12">
      <div class="row">

        <h5 class="form-title"><%= t('ideas.edit.title') %></h5>

        <%= simple_form_for [@idea] do |f| %>
          <div class="row">
            <div class="form">
              <%= f.error_notification %>

              <div class="col s10">
                <label><%= t('ideas.edit.entity') %></label>
                <select class="select optional initialized browser-default pro_profile_select" name="idea[pro_profile_ids][]" id="idea_pro_profile_ids" multiple="multiple">
                  <% ProProfile.all.each do |pro_profile| %>
                    <option value="<%= pro_profile.id %>" <%= "selected" if @profile_tags.map {|profile_tag| profile_tag.pro_profile_id}.include?(pro_profile.id) %>><%= pro_profile.title %></option>
                  <% end %>
                </select>
              </div>

              <div class="col-xs-2 add-btn">
                <div class="btn">
                  <%= link_to(new_pro_profile_path, data: { confirm: "Attention, si vous continuez les informations de cette idée ne seront pas sauvegardées !"})  do %>
                    <p><img class="logo-form" src="/assets/plus.png"></p>
                  <% end %>
                  <span class="tooltiptext" style="font-size: 8px;"><%= t('ideas.edit.entity') %></span>
                </div>
              </div>

              <div class="col s10">
                <label>git a</label>
                <select class="select optional initialized browser-default box_select" name="idea[box_ids][]" id="idea_box_ids" multiple="multiple">
                  <% Box.all.each do |box| %>
                    <option value="<%= box.id %>" <%= "selected" if @idea_boxes.map {|idea_box| idea_box.box_id}.include?(box.id) %>><%= box.title %></option>
                  <% end %>
                </select>
              </div>

              <div class="col-xs-2 add-btn">
                <div class="btn">
                  <%= link_to(new_box_path, data: { confirm: "Attention, si vous continuez les informations de cette idée ne seront pas sauvegardées !"}) do %>
                    <p><img class="logo-form" src="/assets/plus.png"></p>
                  <% end %>
                  <span class="tooltiptext" style="font-size: 8px;"><%= t('ideas.edit.box_idea') %></span>
                </div>
              </div>

              <%= f.input :title, label: t('ideas.new.title2'), wrapper_html: {class: 's12'} %>

              <%= f.input :description, wrapper_html: {class: 's12', id: 'textarea', maxlength: "240"}, label: t('ideas.new.desc') %>


            </div>
          </div>

          <div class="counter-caractere">
            <p><span id="wordCount" style="color: grey">0 / 240</span></p>
          </div>
          <div style="display: inline" id="icon-localisation">
            <a href="#"><i  class="fas fa-map-marker-alt"></i><%= t('ideas.edit.localize') %></a>
          </div>

          <div id="idea-localisation" style="display: none;">
            <div class="row" >
              <div class="col-xs-12 col-md-4">

                <label><%= t('ideas.edit.countries') %></label>
                <%=  %>
                <select name="idea[country]" class="browser-default countries_select">
                  <option value="" <%= 'selected' if !@idea.country %>><%= t('ideas.edit.cou') %></option>
                  <% CS.countries.delete_if {|k, v| k == :COUNTRY_ISO_CODE}.to_a.sort_by {|c| c[1]}.each do |c| %>
                    <option <%= 'selected' if @idea.country == c[0].to_s %> value="<%= c[0] %>"><%= c[1] %></option>
                  <% end %>
                </select>

              </div>

              <div class="col-xs-12 col-md-4">
                <label><%= t('ideas.edit.region') %></label>
                <select name="idea[state]" class="browser-default states_select">
                  <option value="" selected><%= t('ideas.edit.region') %></option>
                </select>
              </div>

              <div class="col-xs-12 col-md-4">
                <label><%= t('ideas.edit.city') %></label>
                <select name="idea[city]" class="browser-default cities_select">
                  <option value="" selected><%= t('ideas.edit.city') %></option>
                </select>
              </div>
          </div>
          <input type="hidden" name="selectedState" value="<%= @idea.state %>">
          <input type="hidden" name="selectedCity" value="<%= @idea.city %>">
        </div>

        <div class="row">
          <div class="col-xs-3">
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <%#= f.input :photo, class: "btn" %>
          </div>

          <div class="col-xs-3">
            <div class="form-actions text-center" style="margin-top: 9px;">
              <button name="commit" type="submit" value="Sauvegarder" class="btn save-btn" style="
              height: 41px;">
                <img class="logo-form" src="/assets/save-eb4546cc946a82a59f912aaf85b9028563bbf001c5dadbd0f78bd5c0bec78ef3.png">
              </button>
            </div>
          </div>

          <div class="col-xs-4">
            <div class="form-actions text-center post-btn" style="margin-top: 14px;">
              <%= f.button :submit, t('ideas.edit.btn') %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-2">
              <% if policy(@idea).destroy? %>
                <%= link_to idea_path(@idea), method: :delete, data: {confirm: "Êtes-vous sûr(e) de vouloir supprimer cette idée ?"} do %>
                  <div class="form-actions text-center btn post-btn delete-btn">
                    <img class="logo-form" src="/assets/garbage.png">
                  </div>
                <% end %>
              <% end %>
            </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js">
      $(document).ready(function () {
          $('select').formSelect();
      });
  </script>

app/views/ideas/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="type-selection text-center">
      <a id="date-btn" href="#">
        <div class="filter <%= "active" if params[:order] == "date" || request.fullpath == "/" %>">
          <p><%= t('ideas.index.date') %></p>
        </div>
      </a>
      <a id="popularity-btn" href="#">
        <div class="filter <%= "active" if params[:order] == "popularity" %>">
          <p><%= t('ideas.index.popularity') %></p>
        </div>
      </a>
      <a id="rating-btn" href="#">
        <div class="filter <%= "active" if params[:order] == "rating" %>">
          <p><%= t('ideas.index.top') %></p>
        </div>
      </a>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <%= form_tag ideas_path, method: :get, :class => 'search-bar' do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: t('ideas.index.recherche')
      %>
      <%= submit_tag "🔍", class: "btn search-icon" %>
    <% end %>
  </div>
</div>

<div class="hidden-sm hidden-md hidden-lg">
  <div class="row">
    <div class="col-xs-12">
      <div style="display: inline" id="icon-localisation">
        <a href="#"><i  class="fas fa-map-marker-alt"></i> <%= t('ideas.index.recherche') %></a>
      </div>
    </div>
  </div>
  <div id="idea-localisation" style="display: none;">
    <div class="col-xs-12">
      <form id="filter-form" action="/ideas/filter" method="post">
        <label><%= t('ideas.index.countries') %> <%= params[:country] %></label>
        <select name="country" class="browser-default countries_select">
          <option value="" disabled <%= 'selected' if !params[:country] %>><%= t('ideas.index.countries') %></option>
          <% CS.countries.delete_if {|k, v| k == :COUNTRY_ISO_CODE}.to_a.sort_by {|c| c[1]}.each do |c| %>
            <option <%= 'selected' if params[:country] == c[0].to_s %> value="<%= c[0] %>"><%= c[1] %></option>
          <% end %>
        </select>
      </div>
      <div class="col-xs-12">
        <label><%= t('ideas.index.region') %></label>
        <select name="state" class="browser-default states_select">
          <option value="" disabled selected><%= t('ideas.index.region') %></option>
        </select>
      </div>
      <div class="col-xs-12">
        <label><%= t('ideas.index.city') %></label>
        <select name="city" class="browser-default cities_select">
          <option value="" disabled selected><%= t('ideas.index.city') %></option>
        </select>
      </div>
      <div class="col-xs-12">
        <button class="waves-effect waves-light btn filter-btn" type="submit"><%= t('ideas.index.filter') %></button>
      </div>
      <input type="hidden" name="order" value="<%= params[:order] %>">
    </form>
    <input type="hidden" name="selectedState" value="<%= params[:state] %>">
    <input type="hidden" name="selectedCity" value="<%= params[:city] %>">
  </div>
  </div>
</div>
<div class="main-container">
  <div class="my-container">
    <div class="row">
      <% if !@ideas.empty? %>
        <% @ideas.each do |idea| %>
          <div class="col-sm-12 col-md-7 col-md-offset-3">
            <%= render 'shared/card_idea', idea: idea %>
          </div>
        <% end %>
      <% elsif @ideas.empty? %>
        <div class="col-sm-12 col-md-7 col-md-offset-3">
          <%= render 'shared/empty_card_idea' %>
        </div>
      <% end %>
    </div>
  </div>
    <div id="card-filter" class="hidden-xs">
      <div class="col-xs-12">
        <form id="filter-form" action="/ideas/filter" method="post">
          <label>Pays <%= params[:country] %></label>
          <select name="country" class="browser-default countries_select">
            <option value="" disabled <%= 'selected' if !params[:country] %>><%= t('ideas.index.countries') %></option>
            <% CS.countries.delete_if {|k, v| k == :COUNTRY_ISO_CODE}.to_a.sort_by {|c| c[1]}.each do |c| %>
              <option <%= 'selected' if params[:country] == c[0].to_s %> value="<%= c[0] %>"><%= c[1] %></option>
            <% end %>
          </select>
        </div>
        <div class="col-xs-12">
          <label>Région</label>
          <select name="state" class="browser-default states_select">
            <option value="" disabled selected><%= t('ideas.index.region') %></option>
          </select>
        </div>
        <div class="col-xs-12">
          <label>Ville</label>
          <select name="city" class="browser-default cities_select">
            <option value="" disabled selected><%= t('ideas.index.city') %></option>
          </select>
        </div>
        <div class="col-xs-12">
          <button class="waves-effect waves-light btn filter-btn" type="submit"><%= t('ideas.index.filter') %></button>
        </div>
        <input type="hidden" name="order" value="<%= params[:order] %>">
      </form>
      <input type="hidden" name="selectedState" value="<%= params[:state] %>">
      <input type="hidden" name="selectedCity" value="<%= params[:city] %>">
    </div>
  </div>

app/views/ideas/new.html.erb
<div class="container">
  <div class="col s12">
    <div class="row">

      <h5 class="form-idea-title text-center"><%= t('ideas.new.title1') %></h5>
      <%= simple_form_for [@idea] do |f| %>
        <div class="row">
          <div class="form">
            <%= f.error_notification %>

            <div class="col s10">
              <label><%= t('ideas.edit.entity') %></label>
              <select class="select optional initialized browser-default pro_profile_select" name="idea[pro_profile_ids][]" id="idea_pro_profile_ids" multiple="multiple">
                <% ProProfile.all.each do |entity| %>
                  <option value="<%= entity.id %>"><%= entity.title %></option>
                <% end %>
              </select>
            </div>

            <div class="col-xs-2 add-btn">
              <div class="btn">
                <%= link_to(new_pro_profile_path, data: { confirm: "Attention, si vous continuez les informations de cette idée ne seront pas sauvegardées !"})  do %>
                  <p><img class="logo-form" src="/assets/plus.png"></p>
                <% end %>
                <span class="tooltiptext" style="font-size: 8px;"><%= t('ideas.new.add_entity') %></span>
              </div>
            </div>

            <div class="col s10">
              <label><%= t('ideas.edit.box_idea') %></label>
              <select class="select optional initialized browser-default box_select" name="idea[box_ids][]" id="idea_box_ids" multiple="multiple">
                <% Box.all.each do |box| %>
                  <option value="<%= box.id %>"><%= box.title %></option>
                <% end %>
              </select>
            </div>

            <div class="col-xs-2 add-btn">
              <div class="btn">
                <%= link_to(new_box_path, data: { confirm: "Attention, si vous continuez les informations de cette idée ne seront pas sauvegardées !"}) do %>
                  <p><img class="logo-form" src="/assets/plus.png"></p>
                <% end %>
                <span class="tooltiptext" style="font-size: 8px;"><%= t('ideas.new.add_idea_box') %></span>
              </div>
            </div>

            <%= f.input :title, label: t('ideas.new.title2'), wrapper_html: {class: 's12'} %>

            <%= f.input :description, wrapper_html: {class: 's12', id: 'textarea', maxlength: "240"}, label: t('ideas.new.desc') %>

          </div>
        </div>

        <div class="counter-caractere">
          <p><span id="wordCount" style="color: grey">0 / 240</span></p>
        </div>
        <div style="display: inline" id="icon-localisation">
          <a href="#"><i  class="fas fa-map-marker-alt"></i> <%= t('ideas.edit.localize') %></a>
        </div>

        <div id="idea-localisation" style="display: none;">
          <div class="row" >
            <div class="col-xs-12 col-md-4">

              <label><%= t('ideas.edit.countries') %></label>
              <select name="idea[country]" class="browser-default countries_select">
                <option value="" disabled <%= 'selected' if !params[:country] %>><%= t('ideas.edit.countries') %></option>
                <% CS.countries.delete_if {|k, v| k == :COUNTRY_ISO_CODE}.to_a.sort_by {|c| c[1]}.each do |c| %>
                  <option <%= 'selected' if params[:country] == c[0].to_s %> value="<%= c[0] %>"><%= c[1] %></option>
                <% end %>
              </select>

            </div>

            <div class="col-xs-12 col-md-4">
              <label>Région</label>
              <select name="idea[state]" class="browser-default states_select">
                <option value="" disabled selected><%= t('ideas.edit.region') %></option>
              </select>
            </div>

            <div class="col-xs-12 col-md-4">
              <label>Ville</label>
              <select name="idea[city]" class="browser-default cities_select">
                <option value="" disabled selected><%= t('ideas.edit.city') %></option>
              </select>
            </div>
          </div>
        </div>


        <div class="row">
          <div class="col-xs-3">

            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>

          </div>

          <div class="col-xs-3">
            <div class="form-actions text-center" style="margin-top: 9px;">
              <button name="commit" type="submit" value="Sauvegarder" class="btn save-btn" style="
              height: 41px;">
                <img class="logo-form" src="/assets/save-eb4546cc946a82a59f912aaf85b9028563bbf001c5dadbd0f78bd5c0bec78ef3.png">
              </button>
            </div>
          </div>

          <div class="col-xs-6">
            <div class="form-actions text-center post-btn" style="margin-top: 14px;">
              <%= f.button :submit, t('ideas.new.btn') %>
            </div>
          </div>

        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js">
    $(document).ready(function () {
        $('select').formSelect();
    });
</script>

app/views/ideas/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= render 'shared/card_idea', idea: @idea %>
    </div>
    </div>
  </div>
</div>

<div class="container">
  <%= render 'reviews/form', idea: @idea, review: @review %>
</div>

<div class="container">
  <div class="reviews-idea-show" >
    <% if !@idea.reviews.empty? %>
      <p><%= t('ideas.show.last_reviews') %></p>
    <% end %>
    <% @idea.reviews.order(created_at: :desc).each do |review|%>
    <div class="card-reviews-idea">
      <div class="infos-reviews-idea">
        <div class="username-author-review-idea">
          <b><%= review.profile.username %></b>
        </div>
        <div class="date review-idea">
          <b><%= review.created_at.strftime("%B %d, %Y")  %></b>
        </div>
      </div>
      <div class="description-review-idea">
        <%= review.description %>
      </div>
      <%= link_to (reviews_upvote_path(review)), id: 'upvote-btn', method: :post do %>
        <% if review.users_array.include?([@user.id.to_s, review.id.to_s]) %>
          <i class="fas fa-heart"></i>
        <% else %>
          <i class="far fa-heart"></i>
        <% end %>
      <% end %>
      <%= review.upvote %>
      <% if policy(review).update? %>
        <%= link_to(edit_idea_review_path(@idea, review)) do %>
          <i class="fas fa-pen"></i>
        <% end %>
      <% end %>
      <% if policy(review).destroy? %>
        <%= link_to idea_review_path(@idea, review), method: :delete do %>
          <i class="fas fa-trash"></i>
        <% end %>
      <% end %>
      <% if review.photo.url  %>
        <%= image_tag review.photo.url(:bright_face) %>
      <% end %>

    </div>
    <% end %>
  </div>
</div>

<script src="/assets/jquery.js" type="text/javascript"></script>
<script src="/assets/jquery_ujs.js" type="text/javascript"></script>

app/views/ideas/update.html.erb
<h1>Ideas#update</h1>
<p>Find me in app/views/ideas/update.html.erb</p>