config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
           :controllers  => {
             :registrations => 'my_devise/registrations',
             :omniauth_callbacks => 'users/omniauth_callbacks'

           }

  resources :bookmarks, only: [:index, :new, :destroy]

  post 'reviews/upvote'
  post 'ideas/filter', to: "ideas#index"

  scope '(:locale)', locale: /fr|en/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    post '/rate' => 'rater#create', :as => 'rate'
    # get 'bookmarks/index'
    # get 'bookmarks/new'
    # get 'bookmarks/destroy'


    resources :pro_profiles
    resources :boxes
    resources :ideas  do
      resources :reviews
    end



    get 'ideas/index_rating'

    resources :profiles

    # post 'profiles/bookmark'
    # post 'profiles/bookmarked_ideas'
    get 'states', to: 'profiles#states'
    get 'cities', to: 'profiles#cities'
    get 'my_profile', to: 'profiles#my_profile'

    get 'cgu', to: 'pages#cgu'


    root to: 'ideas#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/box.rb
class Box < ApplicationRecord
  belongs_to :profile
  has_many :idea_boxes
  has_many :ideas

  validates :title,
          :presence => {:message => "Vous devez ajouter un nom à votre boite à idée" },
          :uniqueness => {:message => "Ce nom existe déjà"},
          :length => { :maximum => 40, :message => "Votre titre doit avoir moins de 40 caractères"}
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController

  before_action :set_box, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = " \
        boxes.title ILIKE :query \
        OR boxes.description ILIKE :query \
      "
      @boxes = policy_scope(Box).where(sql_query, query: "%#{params[:query]}%")
    else
      @boxes = policy_scope(Box)
    end
  end

  def show
    authorize @box
  end

  def new
    @box = Box.new
    authorize @box
  end

  def create
    @user = User.find(current_user.id)
    @profile = Profile.find_by(user_id: @user.id)
    @box = Box.new(box_params)
    authorize @box
    @box.profile_id = @profile.id
    if @box.valid?
      @box.save
      redirect_to box_path(@box)
    else
      render :new
    end
  end

  def edit
    authorize @box
  end

  def update
    @box.update(box_params)
    authorize @box
    if @box.valid?
      @box.save
      redirect_to box_path(@box)
    else
      render :new
    end
  end

  def destroy
    authorize @box
    @box.destroy
  end

  private

  def box_params
    params.require(:box).permit(:title, :description)
  end

  def set_box
    @box = Box.find(params[:id])
  end
end

app/views/boxes/create.html.erb
<h1>Boxes#create</h1>
<p>Find me in app/views/boxes/create.html.erb</p>

app/views/boxes/destroy.html.erb
<h1>Boxes#destroy</h1>
<p>Find me in app/views/boxes/destroy.html.erb</p>

app/views/boxes/edit.html.erb
<div class="hidden-xs" style="margin-top: 100px;">
</div>
<div class="container">
  <div class="col s12">
    <div class="row">
      <div class="card form-card form-card-pro-profile col-sm-6">
        <h5 class="form-title text-center"><%= t('boxes.edit.title') %></h5>

        <%= simple_form_for [@box] do |f| %>

          <div class="row">
            <div class="form">
              <%= f.error_notification %>

              <%= f.input :title,
                          label: 'Titre',
                          class: "title-label",
                          wrapper_html: { class: 's12 input-field' } %>

              <%= f.input :description,
                          label: 'Description',
                          class: "title-label",
                          wrapper_html: { class: 's12' } %>
            </div>
          </div>
          <div class="form-actions text-center">
            <%= f.button :submit, t('boxes.edit.button') %>
          </div>
        <% end %>
      </div>
      <div class="col-xs-6 hidden-xs">
        <%= image_tag("idea_box.png", :class => "idea-img-form") %>
      </div>
    </div>
  </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems, options);
    });
</script>

app/views/boxes/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="type-selection text-center">
      <%= link_to(pro_profiles_path) do %>
        <div class="filter <%= current_class?(pro_profiles_path) %>">
          <p><%= t('boxes.index.entity') %></p>
        </div>
      <% end %>
      <%= link_to(boxes_path) do %>
        <div class="filter <%= current_class?(boxes_path) %>">
          <p><%= t('boxes.index.box_ideas') %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <%= form_tag boxes_path, method: :get, :class => 'search-bar' do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: t('boxes.index.search')
      %>
      <%= submit_tag "🔍", class: "btn search-icon" %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <% if @boxes %>
      <% @boxes.each do |box| %>
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
          <div class="row">
            <div class="col s12">
              <div class="card">
                <div class="card-image">
                  <%= image_tag("box.png", :class => "card-idea-logo") %>
                  <%= image_tag("idea_box.png", :class => "idea-image") %>
                  <%= link_to (profile_path(Profile.find(box.profile_id))) do %>
                    <p class="author-name box-author-name"><%= t('boxes.index.by') %> <%= Profile.find(box.profile_id).username %>
                  <% end %>
                  </p>
                  <%= link_to (box_path(box)) do %>
                    <span class="card-title box-title"><%= box.title %><br><%= IdeaBox.where(box_id: box.id).count %> <%= t('boxes.index.number_ideas') %></span>
                  <% end %>
                  <% if policy(box).edit? %>
                    <%= link_to(edit_box_path(box)) do %>
                      <i class="fas fa-pen card-idea-pencil" style="color: black;"></i>
                    <% end %>
                  <% end %>
                </div>
                <div class="card-content">
                  <p>
                    <%= box.description %>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/boxes/new.html.erb
<div class="hidden-xs" style="margin-top: 100px;">
</div>
<div class="container">
  <div class="col s12">
    <div class="row">
      <div class="card form-card form-card-pro-profile col-sm-6">

        <h5 class="form-title text-center"> <%= t('boxes.new.title') %> </h5>

        <%= simple_form_for [@box] do |f| %>

          <div class="row">
            <div class="form">
              <%= f.error_notification %>

              <%= f.input :title,
                          label: t('boxes.new.name'),
                          class: "title-label",
                          wrapper_html: { class: 's12 input-field' } %>

              <%= f.input :description,
                          label: 'Description',
                          class: "title-label",
                          wrapper_html: { class: 's12' } %>
            </div>
          </div>
          <div class="form-actions text-center">
            <%= f.button :submit, t('boxes.new.btn') %>
          </div>
          <% end %>
          </div>
      <div class="col-xs-6 hidden-xs">
        <%= image_tag("idea_box.png", :class => "idea-img-form") %>
      </div>
    </div>
  </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems, options);
    });
</script>

app/views/boxes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= render 'shared/card_box', box: @box %>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
      <% IdeaBox.where(box_id: @box.id).each do |idea_box| %>
        <% idea = Idea.find(idea_box.idea_id) %>
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
          <%= render 'shared/card_idea', idea: idea %>
        </div>
      <% end %>
  </div>
</div>

app/views/boxes/update.html.erb
<h1>Boxes#update</h1>
<p>Find me in app/views/boxes/update.html.erb</p>