config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
           :controllers  => {
             :registrations => 'my_devise/registrations',
             :omniauth_callbacks => 'users/omniauth_callbacks'

           }

  resources :bookmarks, only: [:index, :new, :destroy]

  post 'reviews/upvote'
  post 'ideas/filter', to: "ideas#index"

  scope '(:locale)', locale: /fr|en/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    post '/rate' => 'rater#create', :as => 'rate'
    # get 'bookmarks/index'
    # get 'bookmarks/new'
    # get 'bookmarks/destroy'


    resources :pro_profiles
    resources :boxes
    resources :ideas  do
      resources :reviews
    end



    get 'ideas/index_rating'

    resources :profiles

    # post 'profiles/bookmark'
    # post 'profiles/bookmarked_ideas'
    get 'states', to: 'profiles#states'
    get 'cities', to: 'profiles#cities'
    get 'my_profile', to: 'profiles#my_profile'

    get 'cgu', to: 'pages#cgu'


    root to: 'ideas#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner-profile-description.html.erb
<div class="informations-description">
  <div class="elements-description">
    <p>
      <i class="fas fa-city"></i> <%= @profile.city %>
    </p>
  </div>
  <br>
  <div class="elements-description">
    <p>
      <i class="fas fa-venus-mars"></i> <%= @profile.sexe %>
    </p>
  </div>
  <br>
  <div class="elements-description">
    <p>
      <i class="fas fa-birthday-cake"></i> <%= @profile.age %> ans
    </p>
  </div>
  <br>
  <div class="elements-description">
    <p>
      <%= @profile.description %>
    </p>
  </div>
</div>

app/views/shared/_banner-profile.html.erb
<div class="text-center">
  <div class="col-sm-6 col-xs-6 text-center">
    <div class="banner-profile">
      <div class="text-center">
        <div class="avatar-position">
          <p>
            <div class="dropdown">
              <% if @profile.photo.url %>
              <%= image_tag @profile.photo.url(:bright_face) %>
              <% else %>
              <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
              <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <% end %>
            </div>
          </p>
          </div>
        </div>
        <div class="username text-center">
          <%= @profile.username %>
          <%= link_to edit_profile_path(@profile) do %>
           <p class="edit-user"><i class="fas fa-user-edit" style="color: white;"></i></p>
          <% end %>
        </div>
        <div class="username text-center">

        <%= link_to(destroy_user_session_path, :method=>'delete') do %>
        <p><i class="fas fa-sign-out-alt" style="color: #000000;"></i></p>
        <% end %>



      </div>
    </div>
  </div>
  <div class="col-sm-6 col-xs-6 text-center">
    <div class="data-position">
      <div class="elements-description">
        <p>
          <b>Pseudo :</b> <%= @profile.username %>
        </p>
      </div>
      <br>
      <div class="elements-description">
        <p>
          <b> Ville :</b> <%= @profile.city %>
        </p>
      </div>
      <br>
      <div class="elements-description">
        <p>
          <b>Sexe :</b> <%= @profile.sexe %>
        </p>
      </div>
      <br>
      <div class="elements-description">
        <p>
          <b>Âge :</b> <%= @profile.age %> ans
        </p>
      </div>
      <br>
      <div class="elements-description">
        <p>
          <%= @profile.description %>
        </p>
      </div>
    </div>
  </div>
  </div>
<div class="row links">
  <div class="col-xs-6">
    <div class="btn">
      <%= link_to(new_pro_profile_path) do %>
        <p>+ entité</p>
      <% end %>
    </div>
  </div>
  <div class="col-xs-6">
    <div class="btn">
      <%= link_to(new_box_path) do %>
        <p>+ boite à idée</p>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <div class="type-selection text-center">
      <%= link_to(root_path) do %>
        <div class="filter <%= current_class?(root_path) %>">
          <p>Date</p>
        </div>
      <% end %>
      <a href="?popularity">
        <div class="filter <%= current_class?('/?popularity') %>">
          <p>Popularité</p>
        </div>
      </a>
      <a href="?rating">
        <div class="filter <%= current_class?('/?rating') %>">
          <p>Top</p>
        </div>
      </a>
    </div>
  </div>
</div>

<div class="col-xs-12">
  <div class="back-color-show">
    <ul class="ul-link-show">
      <li class="link-show">
      <a href="?idees">
        <div class="filtre<%= " active" if params.has_key?("idee") %>">
          <p><strong>Idées</strong></p>
        </div>
      </a>
      </li >
      <li class="link-show">
      <a href="?boiteidees">
        <div class="filtre<%= " active" if params.has_key?("boiteidees") %>">
          <p><strong>Boîtes à idées</strong></p>
        </div>
      </a>
      </li>
      <li class="link-show">
      <a href="?profile">
        <div class="filtre<%= " active" if params.has_key?("profile") %>">
          <p><strong>Profile</strong></p>
        </div>
      </a>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_card_box.html.erb
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-image">
        <%= image_tag("box.png", :class => "card-idea-logo") %>
        <%= image_tag("idea_box.png", :class => "idea-image") %>
        <%= link_to (profile_path(Profile.find(box.profile_id))) do %>
          <p class="author-name box-author-name">Par <%= Profile.find(box.profile_id).username %>
        <% end %>
        </p>
        <%= link_to (box_path(box)) do %>
          <span class="card-title box-title"><%= box.title %><br><%= IdeaBox.where(box_id: box.id).count %> idées</span>
        <% end %>
        <% if policy(box).edit? %>
          <%= link_to(edit_box_path(box)) do %>
            <i class="fas fa-pen card-idea-pencil" style="color: black;"></i>
          <% end %>
        <% end %>
      </div>
      <div class="card-content">
        <p>
          <%= box.description %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card_idea.html.erb
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-image" style="background-color: rgba(135, 174, 180, 0.5);">
        <%= image_tag("card-idea-logo.png", :class => "card-idea-logo") %>
        <% if idea.photo.url %>
          <%= image_tag(idea.photo.url, :class => "idea-image") %>
        <% elsif  %>
          <%= image_tag("idea-2.jpg", :class => "idea-image") %>
        <% end %>
        <%= link_to (profile_path(Profile.find(idea.profile_id))) do %>
          <p class="author-name"><%= t('ideas.index.by') %>
            <%= Profile.find(idea.profile_id).username %>
        <% end %>
        <% if !ProfileTag.all.where(idea_id: idea.id).empty? %>
          à
        <% end %>
        <% ProfileTag.all.where(idea_id: idea.id).each do |profile_tag| %>
          <%= link_to (pro_profile_path(ProProfile.find(profile_tag.pro_profile_id))) do %>
            <%= ProProfile.find(profile_tag.pro_profile_id).title %>
            <% if ProfileTag.all.where(idea_id: idea.id).count > 1 %>
              /
            <% end %>
          <% end %>
        <% end %>
        </p>
        <p class="idea-date"> <%= idea.created_at.strftime("%B %d, %Y") %></p>

        <%= link_to (idea_path(idea)) do %>
          <span class="card-title"><%= idea.title %></span>
        <% end %>
        <% if idea.city %>
          <p class="idea-city"><i class="fas fa-map-marker-alt"></i> <%= idea.city %> </p>
        <% end %>

        <% @bookmark = Bookmark.find_by(idea_id: idea.id) %>

        <% if current_user.present? && Profile.where(user: current_user.id).exists? %>
          <% if policy(idea).edit? %>
            <%= link_to(edit_idea_path(idea)) do %>
              <i class="fas fa-pen card-idea-pencil"></i>
            <% end %>
          <% else %>
            <% if Bookmark.find_by(profile_id: Profile.find_by(user_id: current_user.id).id) && @bookmark %>
                <%= link_to bookmark_path(@bookmark), method: :delete do %>
                  <i class="card-idea-bookmark fas fa-bookmark"></i>
                <% end %>
              <% else %>
                <%= link_to (new_bookmark_path(idea)) do %>
                  <i class="card-idea-bookmark far fa-bookmark"></i>
                <% end %>
              <% end %>
            <% end %>
          <% end %>

        <%= link_to (profile_path(Profile.find(idea.profile_id))) do %>
          <% if Profile.find(idea.profile_id).photo.url %>
            <%= image_tag(Profile.find(idea.profile_id).photo.url, :class => "avatar-little") %>
          <% else %>
            <%= image_tag("avatar-default.png", :class => "avatar-little") %>
          <% end %>
        <% end %>

        <% if !ProfileTag.all.where(idea_id: idea.id).empty? %>
          <i class="fas fa-chevron-right"></i>
        <% end %>
        <% ProfileTag.all.where(idea_id: idea.id).each do |profile_tag| %>
          <% if ProProfile.find(profile_tag.pro_profile_id).photo.url %>
            <%= link_to (pro_profile_path(ProProfile.find(profile_tag.pro_profile_id))) do %>
              <%= image_tag(ProProfile.find(profile_tag.pro_profile_id).photo.url, :class => "tag-avatar") %>
            <% end %>
          <% else %>
            <%= link_to (pro_profile_path(ProProfile.find(profile_tag.pro_profile_id))) do %>
              <%= image_tag("company.png", :class => "tag-avatar") %>
            <% end %>
          <% end %>
        <% end %>

      </div>

      <div class="card-descriptions">
        <p><%= idea.description %>
        </p>
        <br>
      </div>


      <div class="rate text-center">
        <%= rating_for idea, 'rate', cancel_place: 'right', cancel_hint: 'Cancel this vote!', enable_half: true %>
        <p><%= Rate.avg(idea).round(1) %> / 5 - <%= Rate.where(rateable_id: idea.id).count %> vote<%= "s" if Rate.where(rateable_id: idea.id).count > 1 %></p>
      </div>

      <div class="row">
        <div class="col-xs-12">
          <div class="row" style="margin-bottom: -31px;">
            <div class="card-idea-tags">
              <% IdeaBox.all.where(idea_id: idea.id).each do |idea_box| %>
                <%= link_to box_path(Box.find(idea_box.box_id)), class: "card-box-tag" do %>
                  <p>#<%= Box.find(idea_box.box_id).title %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <hr>

      <div class="card-details">
        <div class="row">
          <div class="col-xs-6 text-center">
            <%= link_to (idea_path(idea)) do %>
              <i class="far fa-comment"></i> <%= t('ideas.index.comment') %>
            <% end %>
          </div>
          <div class="col-xs-6 text-center">
            <%= link_to (idea_path(idea)) do %>
              <i class="fas fa-search"></i> <%= t('ideas.index.see') %>
            <% end %>
          </div>
        </div>
          <hr>
          <div class="comment-number">
            <%= link_to (idea_path(idea)) do %>
              <%= idea.reviews.count %>
              <% if idea.reviews.count > 1 %>
                <%= t('ideas.index.count_comments') %>
              <% else %>
                <%= t('ideas.index.count_comment') %>
              <% end %>
            <% end %>
          </div>
          <% idea.reviews.order(created_at: :desc).first(1).each do |element| %>
            <div class="row">
              <div class="col-xs-2">
                <div class="avatar-author"><%= Profile.find(element.profile_id).username.first(1).capitalize %></div>
              </div>
              <div class="col-xs-10 ">
                <p class="comment-preview">
                  <%= element.description.first(50) %>
                  <% if element.description.size >= 50 %>
                    ...
                  <% end %>
                </p>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card_idea_profile_show.html.erb
<% @profile.ideas.each do |element| %>
        <div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-image">
        <% if element.photo.url %>
        <%= image_tag element.photo.url%>
        <% end %>
        <p class="author-name"><%= t('profiles.show.by') %> <%= @profile.username %>

        </p>
        <p class="idea-date"> <%= element.created_at.strftime("%B %d, %Y") %></p>
        <span class="card-title"><%= element.title %></span>
        <p class="idea-city">À Lille</p>
        <% if policy(element).edit? %>
          <%= link_to(edit_idea_path(element)) do %>
            <i class="fas fa-pen card-idea-pencil"></i>
          <% end %>
        <% else %>
          <%= link_to (profiles_bookmark_path(element)), method: :post do %>
            <i class="card-idea-bookmark far fa-bookmark"></i>
          <% end %>
        <% end %>
        <img src='https://kitt.lewagon.com/placeholder/users/arthur-littm' class="avatar-little"/>
        <i class="fas fa-chevron-right"></i>
        <%= image_tag("loreal.jpg", :class => "tag-avatar") %>
      </div>
      <div class="card-content">
        <p><%= element.description %></p>
      </div>
      <div class="row">
        <div class="col-xs-6">
        </div>
        <div class="col-xs-6">
          <div class="row">
              <div class="card-idea-tags">
                <% IdeaBox.all.where(idea_id: element.id).each do |idea_box| %>
                  <p class="card-box-tag">#<%= Box.find(idea_box.box_id).title %></p>
                <% end %>
              </div>
          </div>
        </div>
      </div>

      <div class="card-action">
        <a href="#"><i class="far fa-comment"></i></a>
        <a href="#"><i class="far fa-star"></i></a>
        <a href="#"><i class="far fa-eye"></i></a>
        <p class="rating-idea"><%= element.rating %> / 5</p>
        <p class="idea-comment">Voir les 11 commentaires</p>
      </div>
    </div>
  </div>
</div>

    <% end %>

app/views/shared/_card_pro_profile.html.erb
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-image">
        <%= image_tag("company.png", :class => "card-idea-logo") %>
        <% if pro_profile.photo.url %>
          <%= image_tag(pro_profile.photo.url, :class => "idea-image") %>
        <% else %>
          <%= image_tag("idea-2.jpg", :class => "idea-image") %>
        <% end %>
        <%= link_to (profile_path(Profile.find_by(user_id: pro_profile.user_id))) do %>
          <p class="author-name"> <%= t('pro_profiles.show.by') %> <%= Profile.find_by(user_id: pro_profile.user_id).username %></p>
        <% end %>
        <%= link_to (pro_profile_path(pro_profile)) do %>
          <span class="card-title">
            <%= pro_profile.title %>
            <br>
            <%= ProfileTag.where(pro_profile_id: pro_profile.id).count %> <%= t('pro_profiles.show.ideas') %>
          </span>
        <% end %>
        <% if policy(pro_profile).edit? %>
          <%= link_to(edit_pro_profile_path(pro_profile)) do %>
            <i class="fas fa-pen card-idea-pencil"></i>
          <% end %>
        <% end %>
      </div>
      <div class="card-content">
        <p><%= pro_profile.bio %></p>
        <p> </p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_empty_card_idea.html.erb
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-image" style="background-color: rgba(135, 174, 180, 0.5);">
        <%= image_tag("card-idea-logo.png", :class => "card-idea-logo") %>
        <%= image_tag("idea-2.jpg", :class => "idea-image") %>
        </p>
        <span class="card-title">Aucune idée trouvée !</span>
        <%= image_tag("avatar-default.png", :class => "avatar-little") %>

      </div>

      <div class="card-descriptions">
        <p>Postez votre idée facilement sur Ideez
        </p>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
      </div>


      <div class="rate text-center">

      </div>

      <div class="row">
        <div class="col-xs-12">
          <div class="row" style="margin-bottom: -31px;">
            <div class="card-idea-tags">

            </div>
          </div>
        </div>
      </div>

      <hr>

      <div class="card-details">
        <div class="row">
          <div class="col-xs-6 text-center">

          </div>
          <div class="col-xs-6 text-center">

          </div>
        </div>
          <hr>
          <div class="comment-number">

          </div>

      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2014 Copyright Text
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon hidden-xs hidden-sm">
  <!-- Logo -->
  <%= link_to(root_path) do %>
    <div class="logo-navbar-desktop">
      <%= image_tag("idea.png", :class => "logo") %>
      <p class="logo-title">Ideez</p>
    </div>
  <% end %>



  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <div class="row-fluid">
      <div class="col-xs-2 col-xs-offset-1">
        <div class="navbar-wagon-item navbar-wagon-link <%= current_class?(pro_profiles_path) %>">
          <%= link_to pro_profiles_path, style: "fill: white;" do %>
            <%= show_svg 'office.svg' %>
          <% end %>
          <span class="tooltiptext">Entité / boite à idée</span>
        </div>
      </div>


      <!-- NEW IDEA -->
      <% if policy(Idea).create? %>
        <%= link_to(new_idea_path) do %>
          <div class="col-xs-2">
            <div class="navbar-wagon-item navbar-wagon-link <%= current_class?(new_idea_path) %>">
              <%= show_svg 'add.svg' %>
              <span class="tooltiptext">Créer une idée</span>
            </div>
          </div>
        <% end %>
      <% end %>

      <!-- BOOKMARK -->
      <!-- If a user have an account and profile he can see his bookmarked ideas -->

      <% if current_user.present? && Profile.where(user: current_user.id).exists? %>
        <%= link_to(bookmarks_path) do %>
          <div class="col-xs-2">
            <div class="navbar-wagon-item navbar-wagon-link  <%= current_class?(bookmarks_path) %>">
              <%= show_svg 'bookmark.svg' %>
              <span class="tooltiptext">Marque page</span>
            </div>
          </div>
        <% end %>



      <!-- If a user have an account but no profile, he had to create his profile -->

      <% elsif current_user && !@profile %>
        <%= link_to(new_profile_path) do %>
          <div class="col-xs-2">
            <div class="navbar-wagon-item navbar-wagon-link  <%= current_class?(new_idea_path) %>">
              <%= show_svg 'bookmark.svg' %>
              <span class="tooltiptext">Marque page</span>
            </div>
          </div>
        <% end %>

      <!-- If a visitor haven't an account nor a profile, he had to create both. -->

      <% else %>
        <%= link_to(new_user_session_path) do %>
          <div class="col-xs-2">
            <div class="navbar-wagon-item navbar-wagon-link  <%= current_class?(new_idea_path) %>">
              <%= show_svg 'bookmark.svg' %>
              <span class="tooltiptext">Marque page</span>
            </div>
          </div>
        <% end %>
      <% end %>

      <!-- PROFILE SHOW -->

      <!-- If a user have an account and profile -->
      <% if current_user.present? && Profile.where(user: current_user.id).exists? && policy(Profile).show? %>
        <%= link_to(my_profile_path) do %>
          <div class="col-xs-2">
            <div class="navbar-wagon-item navbar-wagon-link <%= current_class?(profile_path(@profile)) %>">
              <%= show_svg 'user.svg' %>
              <span class="tooltiptext">Mon profil</span>
            </div>
          </div>
        <% end %>
      <!-- If a user have an account but no profile -->
      <% elsif current_user.present? && !Profile.where(user: current_user.id).exists? %>
        <%= link_to(new_profile_path) do %>
          <div class="col-xs-2">
            <div class="navbar-wagon-item navbar-wagon-link  <%= current_class?(new_profile_path) %>">
              <%= show_svg 'user.svg' %>
              <span class="tooltiptext">Mon profil</span>
            </div>
          </div>
        <% end %>
      <!-- If a visitor haven't an account nor a profile -->
      <% else %>
        <%= link_to(new_user_session_path) do %>
          <div class="col-xs-2">
            <div class="navbar-wagon-item navbar-wagon-link <%= current_class?(new_profile_path) %>">
              <%= show_svg 'user.svg' %>
              <span class="tooltiptext">Mon profil</span>
            </div>
          </div>
        <% end %>
      <% end %>

        <% if I18n.locale == I18n.default_locale %>
         <div class="col-xs-2">
          <p>
            <%= link_to(:locale=>'en') do  %>
              <%= image_tag("united-kingdom.png", :class => "flag") %>
            <% end  %>
          </p>
          </div>
        <% else %>
          <div class="col-xs-2">
          <p>
            <%= link_to(:locale=>'fr') do  %>
              <%= image_tag("france.png", :class => "flag") %>
            <% end  %>
          </p>
        <%end%>
        </div>
    </div>
  </div>
</div>

<!-- Dropdown appearing on mobile only -->
<div class="hidden-md hidden-lg footer-bar z-depth-1">
  <div class="row-fluid">
    <%= link_to(root_path) do %>
      <div class="col-xs-2 col-xs-offset-1">
        <div class="footer-item navbar-icon <%= current_class?(root_path) %>">
          <%= show_svg 'home.svg' %>
        </div>
      </div>
    <% end %>

    <%= link_to(pro_profiles_path) do %>
      <div class="col-xs-2">
        <div class="footer-item navbar-icon <%= current_class?(pro_profiles_path) %>">
          <%= show_svg 'office.svg' %>
        </div>
      </div>
    <% end %>

    <!-- NEW IDEA -->
    <% if policy(Idea).create? %>
      <%= link_to(new_idea_path) do %>
        <div class="col-xs-2">
          <div class="footer-item navbar-icon <%= current_class?(new_idea_path) %>">
            <%= show_svg 'add.svg' %>
          </div>
        </div>
      <% end %>
    <% end %>

    <!-- BOOKMARK -->

    <!-- If a user have an account and profile he can see his bookmarked ideas -->
    <% if current_user && @profile %> %>
      <%= link_to(bookmarks_path) do %>
        <div class="col-xs-2">
          <div class="footer-item navbar-icon   <%= current_class?(bookmarks_path)%>">
            <%= show_svg 'bookmark.svg' %>
          </div>
        </div>
      <% end %>
    <% elsif current_user.present? && !Profile.where(user: current_user.id).exists? %>
      <%= link_to(new_profile_path) do %>
        <div class="col-xs-2">
          <div class="footer-item navbar-icon   <%= current_class?(bookmarks_path)%>">
            <%= show_svg 'bookmark.svg' %>
          </div>
        </div>
      <% end %>
    <% else %>
      <%= link_to(new_user_session_path) do %>
        <div class="col-xs-2">
          <div class="footer-item navbar-icon <%= current_class?(new_profile_path) %>">
            <%= show_svg 'bookmark.svg' %>
          </div>
        </div>
      <% end %>
    <% end %>

    <%# if policy(Bookmark).index? %>
      <%#= link_to(bookmarks_path) do %>
<!--        <div class="col-xs-2">-->
<!--          <div class="footer-item navbar-icon   <%#= current_class?(bookmarks_path)%>">-->
            <%#= show_svg 'bookmark.svg' %>
<!--          </div>-->
<!--        </div>-->
      <%# end %>
    <%# end %>

    <!-- PROFILE SHOW -->

    <!-- If a user have an account and profile -->
    <% if current_user.present? && Profile.where(user: current_user.id).exists? && policy(Profile).show? %>
      <%= link_to(my_profile_path) do %>
        <div class="col-xs-2">
            <div class="footer-item navbar-icon <%= 'active' if request.fullpath == "/my_profile" || request.fullpath == "/my_profile?ideas" || request.fullpath == "/my_profile?box_idea" || request.fullpath == "/my_profile?pro_profiles" || request.fullpath == "/my_profile?draft" %>">
            <%= show_svg 'user.svg' %>
          </div>
        </div>
      <% end %>
    <!-- If a user have an account but no profile -->
    <% elsif current_user.present? && !Profile.where(user: current_user.id).exists? %>
      <%= link_to(new_profile_path) do %>
        <div class="col-xs-2">
          <div class="footer-item navbar-icon  <%= 'active' if request.fullpath == "/profiles/#{params["id"]}" && Profile.find_by(user_id: current_user.id) == @profile %>">
            <%= show_svg 'user.svg' %>
          </div>
        </div>
      <% end %>
    <!-- If a visitor haven't an account nor a profile -->
    <% else %>
      <%= link_to(new_user_session_path) do %>
        <div class="col-xs-2">
          <div class="footer-item navbar-icon <%= current_class?(new_profile_path) %>">
            <%= show_svg 'user.svg' %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>